#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  3 18:26:08 2020

@author: Matias HW6 Q2
"""

import numpy as np
from scipy.optimize import linprog


#solution to this is x = 5 and y = 6, giving a maximum of 28 within the given constraints
def partA(): #The variables in the vector x (x_1 and x_2), represent the two variables in the function 2x_1 + 3x_2 that we want to maximize given the constraints. i have called them x_1 and x_2 but you may also recognize them as x and y respectively in the previous comment 
    A = np.array([[2, 1], [6, 5], [2, 5]])
    x_1 = x_2 = None
    x = np.array([x_1, x_2])
    b = np.array([18, 60, 40])
    c = np.array([2, 3])
    return A, b, c


def solPrint(A, b, c):
    sol = linprog(-c, A_ub=A, b_ub=b, method='revised simplex')
    final = sol.__getitem__('x')
    print("The solution to the given constrained optimization problem is x = {} and y = {}".format(final[0], final[1]))
    return 
    

if __name__ == '__main__':
    A, b, c = partA()
    solPrint(A, b, c)
